### ISSUE TITLE
Replace Exonet/NTnet

### ISSUE THREAD

**Issue by Andrew-Fall** [PersistentSS13/PersistentOutreach13#8]
The Exonet/NTnet system needs to be replaced to be lore compliant and work in a dynamic and persistent environment.

**Comment by biscuitWizard** [comment]
Exonet should work with ranges across z-levels as appropriate to be compatible with overmap.

**Comment by biscuitWizard** [comment]
file_servers is no longer just a list on the exonet datum. It should be a list of /obj/machinery mainframes with finite storage based on the harddrives inserted into them.

These repositories should actually hold files and programs.

**Comment by biscuitWizard** [comment]
command_consoles in exonet are the basis of a network. every exonet requires one command_console. If the command_console is destroyed, the exonet is also destroyed.

exonet_relays can extend the signal range of command_consoles.

security_consoles can be added to existing exonets to manage permissions.

Doors, machines, etc will use their connected exonet to determine permissions. Permissions for individual mobs can be set using the security_console.

**Comment by biscuitWizard** [comment]
physical access to a security console will always result in the ability to assign permissions to any user. physical security to the console is important.
